name: Docker Website Deploy
on:
    workflow_dispatch
jobs:
    deploy:
        name: Docker Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker Image
              run: |
                docker build --platform linux --tag rtoora/demos-repository:latest .

            - name: Push to DockerHub
              run: |
                docker push rtoora/demos-repository:latest

            - name: App Service Auth
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'docker-demo-site'
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                images: rtoora/demos-repository:latest